require 'snafu/models/glitch_image'
require 'snafu/models/location'
require 'snafu/models/hub'
require 'snafu/models/street'
require 'snafu/models/glitch_time'
require 'snafu/models/achievement'
require 'snafu/models/giant'